<?xml version='1.0' encoding='UTF-8'?>
<ws:definitions name="CustomerCurrentBalance"
                xmlns:ws="http://schemas.xmlsoap.org/wsdl/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:xs="http://www.w3.org/2001/XMLSchema"
                xmlns:tns="http://pensionsoft.ru/schemas/rostelecom/ccstest/"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                targetNamespace="http://pensionsoft.ru/schemas/rostelecom/ccstest/"
                xsi:schemaLocation="
                           http://pensionsoft.ru/schemas/rostelecom/ccstest/
                           http://pensionsoft.ru/schemas/rostelecom/ccstest/ccstest-1.0.xsd">
    <ws:types>
        <xs:schema targetNamespace="http://pensionsoft.ru/schemas/rostelecom/ccstest/">
            <xs:include schemaLocation="ccstest-1.0.xsd"/>
            <xs:element name="CustomerCurrentBalanceRq" type="tns:CustomerCurrentBalanceRqType"/>
            <xs:element name="CustomerCurrentBalanceRs" type="tns:CustomerCurrentBalanceRsType"/>
        </xs:schema>
    </ws:types>

    <ws:message name="CustomerCurrentBalanceRq">
        <ws:part name="request" element="tns:CustomerCurrentBalanceRq"/>
    </ws:message>
    <ws:message name="CustomerCurrentBalanceRs">
        <ws:part name="response" element="tns:CustomerCurrentBalanceRs"/>
    </ws:message>

    <ws:portType name="CustomerCurrentBalancePortType">
        <ws:operation name="CustomerCurrentBalance">
            <ws:input message="tns:CustomerCurrentBalanceRq"/>
            <ws:output message="tns:CustomerCurrentBalanceRs"/>
        </ws:operation>
    </ws:portType>

    <ws:binding name="CustomerCurrentBalanceBinding" type="tns:CustomerCurrentBalancePortType">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <ws:operation name="CustomerCurrentBalance">
            <soap:operation soapAction="http://pensionsoft.ru/schemas/rostelecom/ccstest/CustomerCurrentBalance"/>
            <ws:input><soap:body use="literal"/></ws:input>
            <ws:output><soap:body use="literal"/></ws:output>
        </ws:operation>
    </ws:binding>

    <ws:service name="CustomerCurrentBalanceService">
        <ws:documentation>Запрос текущего баланса абонента</ws:documentation>
        <ws:port name="CustomerCurrentBalancePort" binding="tns:CustomerCurrentBalanceBinding">
            <soap:address location="http://localhost:7001/ccstest-ws-gateway-war/CustomerCurrentBalanceService"/>
        </ws:port>
    </ws:service>
</ws:definitions>